<?php

namespace ContainerYZDtAbM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A4oxCenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A4oxCen' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A4oxCen'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscriptionRepository' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
            'matriculeGenerator' => ['privates', 'App\\utile\\MatriculeGenerator', 'getMatriculeGeneratorService', true],
        ], [
            'inscriptionRepository' => 'App\\Repository\\InscriptionRepository',
            'matriculeGenerator' => 'App\\utile\\MatriculeGenerator',
        ]);
    }
}
