<?php

namespace ContainerYZDtAbM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneNumberTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType' shared service.
     *
     * @return \Misd\PhoneNumberBundle\Form\Type\PhoneNumberType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/odolbeau/phone-number-bundle/src/Form/Type/PhoneNumberType.php';

        return $container->privates['Misd\\PhoneNumberBundle\\Form\\Type\\PhoneNumberType'] = new \Misd\PhoneNumberBundle\Form\Type\PhoneNumberType();
    }
}
