security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            guard:
                authenticators:
                    - App\Security\ClientAuthAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /


    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/users, roles: [ROLE_SUPER_USER] }
        - { path: ^/admin, roles: [ ROLE_USER ] }
        - { path: ^/admin, roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
          ROLE_ADMIN:       ROLE_USER
          ROLE_RESPONSABLE: ROLE_ADMIN
          ROLE_COMMERCIAL:  ROLE_ADMIN
          ROLE_SUPER_USER : [ROLE_ADMIN, ROLE_RESPONSABLE, ROLE_COMMERCIAL, ROLE_ALLOWED_TO_SWITCH]
