swiftmailer:
    transport: smtp
        username: postmaster@sandbox8f299af326894cb684e4e9cd1a2e026a.mailgun.org
        password: 416365bc0bd97bb42c16763608eaf114-2a9a428a-e4debf3c
        host: smtp.mailgun.org
        port: 587
        spool: { type: 'memory' }

