<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'e987b6ab7f8c82ccd87d8fb70b6710bb',
  'MAILER_DSN' => 'sendgrid://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@default',
  'DATABASE_URL' => 'mysql://idy_admin:weex@127.0.0.1:3306/db_kadiOfficial?serverVersion=5.7',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '394db1cd080486065921f9be0c4d7d59',
  'MAILER_URL' => 'smtp://kaaydekkimmo@gmail.com:kadi@2021@localhost:1025',
  'GOOGLE_CLIENT_ID' => '130747449894-nj3iu26q0d4r42ekr8s46lja4j7mbv9c.apps.googleusercontent.com',
  'GOOGLE_CLIENT_SECRET' => 'r9jdq8rdxCpbPUePpvrM2OwY',
  'MAILGUN_API_KEY' => 'replace_me',
);
