# easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Client
#        - App\Entity\DetailsCandidature
#        - App\Entity\
easy_admin_bundle:
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation