<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVCqRF1e\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVCqRF1e/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVCqRF1e.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVCqRF1e\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVCqRF1e\App_KernelProdContainer([
    'container.build_hash' => 'VCqRF1e',
    'container.build_id' => 'd5ff9e61',
    'container.build_time' => 1623838534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVCqRF1e');
