<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWi2FcNC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWi2FcNC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWi2FcNC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWi2FcNC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWi2FcNC\App_KernelProdContainer([
    'container.build_hash' => 'Wi2FcNC',
    'container.build_id' => 'c6d059b2',
    'container.build_time' => 1624004524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWi2FcNC');
