<?php

namespace Container9QvCtb6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RSj2OyIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RSj2OyI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RSj2OyI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notification' => ['privates', 'App\\Notification\\ContactNotification', 'getContactNotificationService', true],
            'property' => ['privates', '.errored..service_locator.RSj2OyI.App\\Entity\\Bien', NULL, 'Cannot autowire service ".service_locator.RSj2OyI": it references class "App\\Entity\\Bien" but no such service exists.'],
        ], [
            'notification' => 'App\\Notification\\ContactNotification',
            'property' => 'App\\Entity\\Bien',
        ]);
    }
}
