<?php

namespace Container5xmQ1Ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBienService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RSj2OyI.App\Entity\Bien' shared service.
     *
     * @return \App\Entity\Bien
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RSj2OyI": it references class "App\\Entity\\Bien" but no such service exists.');
    }
}
