<?php

namespace ContainerXfZXLw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8dS8kbDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8dS8kbD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8dS8kbD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'user' => ['privates', '.errored..service_locator.8dS8kbD.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.8dS8kbD": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'passwordEncoder' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
