<?php

namespace ContainerWi2FcNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\ClientCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\ClientCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\ClientCrudController'] = $instance = new \App\Controller\Admin\ClientCrudController(($container->privates['App\\Service\\CsvService'] ?? ($container->privates['App\\Service\\CsvService'] = new \App\Service\CsvService())));

        $instance->setContainer(($container->privates['.service_locator.7Gh9pQb'] ?? $container->load('get_ServiceLocator_7Gh9pQbService'))->withContext('App\\Controller\\Admin\\ClientCrudController', $container));

        return $instance;
    }
}
