<?php

namespace ContainerWi2FcNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeExtensionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'KevinPapst\AdminLTEBundle\Twig\RuntimeExtension' shared service.
     *
     * @return \KevinPapst\AdminLTEBundle\Twig\RuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['KevinPapst\\AdminLTEBundle\\Twig\\RuntimeExtension'] = new \KevinPapst\AdminLTEBundle\Twig\RuntimeExtension(($container->privates['admin_lte_theme.context_helper'] ?? $container->getAdminLteTheme_ContextHelperService()), $container->parameters['admin_lte_theme.routes']);
    }
}
