<?php

namespace ContainerWi2FcNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensioFrameworkExtra_Psr7_ArgumentValueResolver_ServerRequestService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sensio_framework_extra.psr7.argument_value_resolver.server_request' shared service.
     *
     * @return \Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentValueResolver\Psr7ServerRequestResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Nyholm\Psr7\Factory\Psr17Factory();

        return $container->privates['sensio_framework_extra.psr7.argument_value_resolver.server_request'] = new \Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentValueResolver\Psr7ServerRequestResolver(new \Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory($a, $a, $a, $a));
    }
}
