<?php

namespace ContainerVCqRF1e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ClientFormType' shared autowired service.
     *
     * @return \App\Form\ClientFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ClientFormType'] = new \App\Form\ClientFormType();
    }
}
