<?php

namespace ContainerVCqRF1e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventsExtensionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'KevinPapst\AdminLTEBundle\Twig\EventsExtension' shared service.
     *
     * @return \KevinPapst\AdminLTEBundle\Twig\EventsExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['KevinPapst\\AdminLTEBundle\\Twig\\EventsExtension'] = new \KevinPapst\AdminLTEBundle\Twig\EventsExtension(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['admin_lte_theme.context_helper'] ?? $container->getAdminLteTheme_ContextHelperService()));
    }
}
