<?php

namespace ContainerVCqRF1e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormClientControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FormClientController' shared autowired service.
     *
     * @return \App\Controller\FormClientController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FormClientController'] = $instance = new \App\Controller\FormClientController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\FormClientController', $container));

        return $instance;
    }
}
