<?php

namespace ContainerVCqRF1e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensioFrameworkExtra_Psr7_Listener_ResponseService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sensio_framework_extra.psr7.listener.response' shared service.
     *
     * @return \Sensio\Bundle\FrameworkExtraBundle\EventListener\PsrResponseListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sensio_framework_extra.psr7.listener.response'] = new \Sensio\Bundle\FrameworkExtraBundle\EventListener\PsrResponseListener(new \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory());
    }
}
