<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xmQ1Ax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xmQ1Ax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xmQ1Ax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xmQ1Ax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xmQ1Ax\App_KernelDevDebugContainer([
    'container.build_hash' => '5xmQ1Ax',
    'container.build_id' => 'a8ec8128',
    'container.build_time' => 1623937269,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xmQ1Ax');
