<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7G2fFfs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7G2fFfs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7G2fFfs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7G2fFfs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7G2fFfs\App_KernelDevDebugContainer([
    'container.build_hash' => '7G2fFfs',
    'container.build_id' => '62f9abe7',
    'container.build_time' => 1624882101,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7G2fFfs');
