<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYZDtAbM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYZDtAbM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYZDtAbM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYZDtAbM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYZDtAbM\App_KernelDevDebugContainer([
    'container.build_hash' => 'YZDtAbM',
    'container.build_id' => '1bb71849',
    'container.build_time' => 1625677386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYZDtAbM');
