<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'numero_cin_ou_passeport', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'achat', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'lieu_de_naissance', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nationalite', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'situation_matrimoniale', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'detailsCandidatures', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'agence'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'numero_cin_ou_passeport', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'achat', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'lieu_de_naissance', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nationalite', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'situation_matrimoniale', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'detailsCandidatures', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'agence'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCinOuPasseport(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCinOuPasseport', []);

        return parent::getNumeroCinOuPasseport();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCinOuPasseport(string $numero_cin_ou_passeport): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCinOuPasseport', [$numero_cin_ou_passeport]);

        return parent::setNumeroCinOuPasseport($numero_cin_ou_passeport);
    }

    /**
     * {@inheritDoc}
     */
    public function getAchat(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAchat', []);

        return parent::getAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function addAchat(\App\Entity\Achat $achat): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAchat', [$achat]);

        return parent::addAchat($achat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAchat(\App\Entity\Achat $achat): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAchat', [$achat]);

        return parent::removeAchat($achat);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire(string $commentaire): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(string $tel): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$date_de_naissance]);

        return parent::setDateDeNaissance($date_de_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuDeNaissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuDeNaissance', []);

        return parent::getLieuDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuDeNaissance(string $lieu_de_naissance): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuDeNaissance', [$lieu_de_naissance]);

        return parent::setLieuDeNaissance($lieu_de_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', []);

        return parent::getNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite(string $nationalite): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', [$nationalite]);

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession(string $profession): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationMatrimoniale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationMatrimoniale', []);

        return parent::getSituationMatrimoniale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationMatrimoniale(string $situation_matrimoniale): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationMatrimoniale', [$situation_matrimoniale]);

        return parent::setSituationMatrimoniale($situation_matrimoniale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetailsCandidatures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetailsCandidatures', []);

        return parent::getDetailsCandidatures();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetailsCandidature(\App\Entity\DetailsCandidature $detailsCandidature): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetailsCandidature', [$detailsCandidature]);

        return parent::addDetailsCandidature($detailsCandidature);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetailsCandidature(\App\Entity\DetailsCandidature $detailsCandidature): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetailsCandidature', [$detailsCandidature]);

        return parent::removeDetailsCandidature($detailsCandidature);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?\App\Entity\Ville
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(?\App\Entity\Ville $ville): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor(?string $color): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgence(): ?\App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgence', []);

        return parent::getAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgence(?\App\Entity\Agence $agence): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgence', [$agence]);

        return parent::setAgence($agence);
    }

}
