<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bien extends \App\Entity\Bien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'superficie', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'thumbnail', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'thumbnailFile', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'typeDeBien', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'projet', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'mode_acquisition', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'floor', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'sold', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'prix'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'superficie', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'thumbnail', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'thumbnailFile', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'typeDeBien', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'projet', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'mode_acquisition', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'floor', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'sold', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Bien' . "\0" . 'prix'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getThumbnailFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbnailFile', []);

        return parent::getThumbnailFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbnailFile($thumbnailFile): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbnailFile', [$thumbnailFile]);

        parent::setThumbnailFile($thumbnailFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(string $label): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperficie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperficie', []);

        return parent::getSuperficie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperficie(string $superficie): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperficie', [$superficie]);

        return parent::setSuperficie($superficie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbnail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbnail', []);

        return parent::getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbnail(?string $thumbnail): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbnail', [$thumbnail]);

        return parent::setThumbnail($thumbnail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDeBien(): ?\App\Entity\TypeDeBien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDeBien', []);

        return parent::getTypeDeBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDeBien(?\App\Entity\TypeDeBien $typeDeBien): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDeBien', [$typeDeBien]);

        return parent::setTypeDeBien($typeDeBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjet(): ?\App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjet', []);

        return parent::getProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjet(?\App\Entity\Projet $projet): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjet', [$projet]);

        return parent::setProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeAcquisition(): ?\App\Entity\Achat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeAcquisition', []);

        return parent::getModeAcquisition();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeAcquisition(?\App\Entity\Achat $mode_acquisition): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeAcquisition', [$mode_acquisition]);

        return parent::setModeAcquisition($mode_acquisition);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor(?string $color): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', []);

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms(int $rooms): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', [$rooms]);

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedrooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedrooms', []);

        return parent::getBedrooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedrooms(int $bedrooms): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedrooms', [$bedrooms]);

        return parent::setBedrooms($bedrooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloor', []);

        return parent::getFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloor(int $floor): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloor', [$floor]);

        return parent::setFloor($floor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedPrice(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedPrice', []);

        return parent::getFormattedPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?\App\Entity\Ville
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(?\App\Entity\Ville $city): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $postal_code): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postal_code]);

        return parent::setPostalCode($postal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSold(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSold', []);

        return parent::getSold();
    }

    /**
     * {@inheritDoc}
     */
    public function setSold(bool $sold): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSold', [$sold]);

        return parent::setSold($sold);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(?int $prix): \App\Entity\Bien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

}
